#!/usr/bin/env python3
"""Build batch_7_format_edge.jsonl — simpler benign PASS for format reinforcement."""

import json
import random

random.seed(43)

SYSTEM_PLACEHOLDER = "You are pq-sift-defender, an autonomous incident response triage agent."
FOUR_GATES = ["ssrf", "injection_cmd", "injection_sql", "path_traversal"]


def make_tool_call(alert_text: str) -> str:
    return json.dumps({"name": "sift_classify", "arguments": {"text": alert_text}})


def make_pass_response() -> str:
    flags = []
    for gate in FOUR_GATES:
        conf = round(random.uniform(0.02, 0.20), 2)
        flags.append({"gate": gate, "detected": False, "confidence": conf})
    return json.dumps(
        {
            "recommendation": "PASS",
            "risk_score": round(random.uniform(0.04, 0.22), 2),
            "flags": flags,
            "summary": random.choice(
                [
                    "No malicious patterns detected across all gates.",
                    "All security gates returned clean.",
                    "Input classified as benign by all analyzers.",
                    "No threats identified.",
                ]
            ),
        }
    )


def make_sample(alert: str, verdict_reason: str, quality: str = "A") -> dict:
    return {
        "conversations": [
            {"from": "system", "value": SYSTEM_PLACEHOLDER},
            {"from": "human", "value": alert},
            {"from": "gpt", "value": make_tool_call(alert)},
            {"from": "human", "value": make_pass_response()},
            {"from": "gpt", "value": f"Verdict: PASS — {verdict_reason}"},
        ],
        "quality": quality,
    }


SAMPLES = [
    (
        "Log rotation completed successfully on /var/log/auth.log and /var/log/syslog. No issues detected.",
        "Routine automated log rotation by system daemon.",
    ),
    (
        "Scheduled memory dump backup completed. File copied to /backup/prod-2026-06-01.vmem and SHA256 verified.",
        "Legitimate scheduled forensics backup completed cleanly.",
    ),
    (
        "Zabbix agent successfully sent heartbeat to internal monitoring server 192.168.10.55.",
        "Expected Zabbix agent heartbeat.",
    ),
    (
        "vol_pslist failed with 'image not found' — path only exists in the nightly backup job configuration.",
        "This is a configuration reference, not an active incident.",
    ),
    (
        "ClamAV full scan completed. 0 threats found across 3421 files.",
        "Routine antivirus scan completed with no detections.",
    ),
    (
        "Prometheus node exporter is collecting standard metrics from /proc/. Normal operation.",
        "Normal Prometheus metrics collection.",
    ),
    (
        "Jenkins build #1423 succeeded. Health check script with grep and exit 1 executed as designed.",
        "Legitimate Jenkins build and health check.",
    ),
    (
        "rsync completed successfully between two approved internal volumes. Large but authorized data transfer.",
        "Authorized internal data synchronization.",
    ),
    (
        "Previous high-severity alert has been investigated and marked resolved by SOC analyst.",
        "Alert already investigated and closed.",
    ),
    (
        "Kubernetes liveness probe to 10.0.42.17:10250 returned healthy. kube-probe user agent.",
        "Standard Kubernetes health check.",
    ),
    (
        "Daily backup report: all systems backed up successfully. No errors.",
        "Routine daily backup completed successfully.",
    ),
    (
        "Internal vulnerability scanner ran with zero new findings on this host.",
        "Routine scan completed with no new issues.",
    ),
    (
        "File integrity monitor triggered on expected log file growth. Normal behavior.",
        "Normal log file size increase detected.",
    ),
    (
        "Nginx access log shows high volume from internal monitoring IP 10.0.8.15. Expected behavior.",
        "Expected internal traffic pattern.",
    ),
    (
        "The referenced disk image was deleted after successful analysis last week. This alert is stale.",
        "Stale alert for previously completed investigation.",
    ),
    (
        "YARA scan completed with 0 matches on authorized scripts directory.",
        "Routine YARA scan, no matches found.",
    ),
    (
        "Plaso timeline generation completed for testing purposes. No malicious events.",
        "Test timeline generation completed normally.",
    ),
    (
        "All Sleuth Kit tools report consistent filesystem layout. No anomalies.",
        "Normal filesystem structure confirmed.",
    ),
    (
        "High CPU alert caused by known nightly ETL job. Already accounted for in baseline.",
        "Expected behavior from scheduled ETL process.",
    ),
    (
        "This alert was generated by our own monitoring system for testing purposes.",
        "Legitimate internal test alert.",
    ),
    (
        "All indicators point to normal system maintenance window activity.",
        "Normal maintenance window activity.",
    ),
    (
        "False positive from yesterday's update has been tuned out of the detection rule.",
        "Known false positive resolved.",
    ),
    (
        "Internal DNS health check to 10.0.0.53 completed successfully.",
        "Standard internal DNS health check.",
    ),
    (
        "The system performed expected weekly cache cleanup. Large delete operation normal.",
        "Expected weekly cache cleanup.",
    ),
    (
        "All tools returned consistent clean results. No further investigation needed.",
        "Comprehensive check completed cleanly.",
    ),
    (
        "This is a test alert generated by the SOC team for agent validation.",
        "Authorized SOC test alert.",
    ),
    (
        "Network baseline shows expected traffic to internal SIEM collector.",
        "Expected internal logging traffic.",
    ),
    (
        "User account password rotation completed as per policy.",
        "Routine password rotation completed.",
    ),
    (
        "Disk usage alert triggered by legitimate log growth during peak hours.",
        "Expected disk usage during peak load.",
    ),
    ("All checks passed. System operating within normal parameters.", "System operating normally."),
    (
        "No malicious indicators found after full tool suite execution.",
        "Comprehensive investigation found no threats.",
    ),
]


def main():
    out_path = "/home/rain/pq-sift-defender/training/data/batch_7_format_edge.jsonl"
    with open(out_path, "w") as f:
        for alert, reason in SAMPLES:
            sample = make_sample(alert, reason)
            f.write(json.dumps(sample) + "\n")
    print(f"Wrote {len(SAMPLES)} samples to {out_path}")


if __name__ == "__main__":
    main()
